### ISSUE TITLE
GPU crash with overlay/addons on v0.9.5.4+

### ISSUE THREAD

**Issue by KleyArk** [megai2/d912pxy#110]
**Crash 1**

**Describe the crash**
Game crash and ArcDPS displayed the log file with errors related to D3D9 and DirectX 9.

**To Reproduce**

1. Background apps: Firefox Browser (v65.0.2), Discord
2. Run game
3. Set graphics settings to https://i.imgur.com/t6Wpzru.png
4. Head to "Mystlock Sanctuary"
5. Do this: "Walk near the bank NPC and then open the map"

**Expected behavior**
After you open the map the game starts to stutter for 2-3 seconds and then crashes.

**Standard information**

1. Windows 10 1809 (Build 17763.379)
2. Hardware info: Intel Core i7 4770 (Hyper Threading ON), Nvidia GTX 1080, RAM HyperX DDR3 16GB 1600Mhz
3. Driver version 419.35
4. Addon v0.9.7.5
5. Log file from<game root>/addons/arcdps/arcdps.log

**Addons installed**
ArcDPS (Latest version)
YoloMouse

**Crash Log from ArcDPS**
Mar 17 21:19:31 arcdps 20190309.175644-289-x64
Mar 17 21:19:32 client: gw2 0x7FF75DCB0000-0x7FF7601B8000 (0x9455B404)
Mar 17 21:19:32 client: arcdps 0x7FFEDEDE0000-0x7FFEDEE8B000 (0xF92BCB8D)
Mar 17 21:19:32 client: d3d9 0x7FFECB960000-0x7FFECC1C7000 (0xB648C832)
Mar 17 21:19:32 client: d3d9 is chainload
Mar 17 21:19:33 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 17 21:20:52 error: intercepted crash from client assertion fail, terminating
Mar 17 21:20:52 error: assertion: "..\..\..\Engine\Gr\Dx9\Dx9Tex.cpp", "dstBits", 802

**Additional settings**
Disabled all the optimizations i applied to Nvidia drivers and Gw2-64.exe.

**Additional informations**
Also Discord crashes with the game (No, the problem doesn't depend from Discord).
P.S: Discord's Overlay and Hardware acceleration are disabled.

__________________________________________

**Crash 2**

**Describe the crash**
Game crash and ArcDPS displayed the log file with errors related to D3D9 and DirectX 9.

**To Reproduce**

1. Background apps: Firefox Browser (v65.0.2), Discord
2. Run game
3. Set graphics settings to https://i.imgur.com/t6Wpzru.png
4. Load map "Mystlock Sanctuary"
5. Do this: "Walk around"

**Expected behavior**

**Crash Log from ArcDPS**
Mar 17 21:39:45 arcdps 20190309.175644-289-x64
Mar 17 21:39:46 client: gw2 0x7FF75DCB0000-0x7FF7601B8000 (0x9455B404)
Mar 17 21:39:46 client: arcdps 0x7FFEDEDE0000-0x7FFEDEE8B000 (0xF92BCB8D)
Mar 17 21:39:46 client: d3d9 0x7FFECBF80000-0x7FFECC7E7000 (0xB648C832)
Mar 17 21:39:46 client: d3d9 is chainload
Mar 17 21:39:46 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 17 21:40:46 error: intercepted crash from hardware exception, terminating
Mar 17 21:40:46 error: exception: 0xC0000005, 0x7FFEE691C387, 2

**Crash Log from d912pxy_crash.txt**
SymInit: Symbol-SearchPath: '.;D:\Guild Wars 2;D:\Guild Wars 2;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: ''
OS-Version: 6.2.9200 () 0x100-0x1
D:\Guild Wars 2\Gw2-64.exe:Gw2-64.exe (00007FF75DCB0000), size: 38830080 (result: 0), SymType: '-nosymbols-', PDB: 'D:\Guild Wars 2\Gw2-64.exe', fileVersion: 1.0.0.1
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (00007FFEF6F00000), size: 2019328 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ntdll.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (00007FFEF63D0000), size: 733184 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\KERNEL32.DLL', fileVersion: 6.2.17763.379
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (00007FFEF3210000), size: 2699264 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\KERNELBASE.dll', fileVersion: 6.2.17763.348
C:\Windows\SYSTEM32\apphelp.dll:apphelp.dll (00007FFEF11D0000), size: 573440 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\apphelp.dll', fileVersion: 6.2.17763.292
C:\Windows\System32\USER32.dll:USER32.dll (00007FFEF67C0000), size: 1667072 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\USER32.dll', fileVersion: 6.2.17763.168
C:\Windows\System32\win32u.dll:win32u.dll (00007FFEF2FD0000), size: 131072 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\win32u.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\GDI32.dll:GDI32.dll (00007FFEF6D60000), size: 167936 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\GDI32.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\gdi32full.dll:gdi32full.dll (00007FFEF3020000), size: 1679360 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\gdi32full.dll', fileVersion: 6.2.17763.316
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (00007FFEF34B0000), size: 655360 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\msvcp_win.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (00007FFEF4030000), size: 1024000 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\ucrtbase.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\ADVAPI32.dll:ADVAPI32.dll (00007FFEF6120000), size: 667648 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\ADVAPI32.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\msvcrt.dll:msvcrt.dll (00007FFEF6AC0000), size: 647168 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\msvcrt.dll', fileVersion: 7.0.17763.1
C:\Windows\System32\sechost.dll:sechost.dll (00007FFEF5EC0000), size: 647168 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\sechost.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\RPCRT4.dll:RPCRT4.dll (00007FFEF61D0000), size: 1187840 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\RPCRT4.dll', fileVersion: 6.2.17763.379
C:\Windows\System32\WS2_32.dll:WS2_32.dll (00007FFEF6D90000), size: 446464 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\WS2_32.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\WINTRUST.dll:WINTRUST.dll (00007FFEF3880000), size: 364544 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\WINTRUST.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\MSASN1.dll:MSASN1.dll (00007FFEF2F80000), size: 73728 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\MSASN1.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (00007FFEF3570000), size: 1945600 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\CRYPT32.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (00007FFEEE350000), size: 40960 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\VERSION.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\PSAPI.DLL:PSAPI.DLL (00007FFEF6E00000), size: 32768 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\PSAPI.DLL', fileVersion: 6.2.17763.1
C:\Windows\System32\ole32.dll:ole32.dll (00007FFEF6960000), size: 1396736 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\ole32.dll', fileVersion: 6.2.17763.134
C:\Windows\System32\combase.dll:combase.dll (00007FFEF6490000), size: 3330048 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\combase.dll', fileVersion: 6.2.17763.253
C:\Windows\SYSTEM32\WTSAPI32.dll:WTSAPI32.dll (00007FFEEF8A0000), size: 77824 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\WTSAPI32.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FFEF3800000), size: 516096 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\bcryptPrimitives.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (00007FFEF0140000), size: 147456 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\WINMM.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\OLEAUT32.dll:OLEAUT32.dll (00007FFEF6300000), size: 831488 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\OLEAUT32.dll', fileVersion: 6.2.17763.292
C:\Windows\System32\SHELL32.dll:SHELL32.dll (00007FFEF4820000), size: 21954560 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\SHELL32.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\cfgmgr32.dll:cfgmgr32.dll (00007FFEF31C0000), size: 303104 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\cfgmgr32.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\shcore.dll:shcore.dll (00007FFEF6070000), size: 688128 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\shcore.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\windows.storage.dll:windows.storage.dll (00007FFEF38E0000), size: 7643136 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\windows.storage.dll', fileVersion: 6.2.17763.348
C:\Windows\System32\profapi.dll:profapi.dll (00007FFEF2FA0000), size: 147456 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\profapi.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (00007FFEEFCB0000), size: 184320 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\WINMMBASE.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\powrprof.dll:powrprof.dll (00007FFEF2F20000), size: 380928 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\powrprof.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\shlwapi.dll:shlwapi.dll (00007FFEF42E0000), size: 335872 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\System32\kernel.appcore.dll:kernel.appcore.dll (00007FFEF2F00000), size: 69632 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\System32\cryptsp.dll:cryptsp.dll (00007FFEF3550000), size: 94208 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\SYSTEM32\MSACM32.dll:MSACM32.dll (00007FFEEFBB0000), size: 114688 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17763.379_none_36a32ecd61af0e6f\gdiplus.dll:gdiplus.dll (00007FFEE8E50000), size: 1724416 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.379
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17763.379_none_10e5882c642d5588\COMCTL32.dll:COMCTL32.dll (00007FFEE95D0000), size: 692224 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 5.82.17763.379
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\SYSTEM32\USP10.dll:USP10.dll (00007FFEEFB70000), size: 102400 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\SYSTEM32\MSIMG32.dll:MSIMG32.dll (00007FFEEA070000), size: 28672 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\SYSTEM32\Secur32.dll:Secur32.dll (00007FFEE3F70000), size: 49152 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\Secur32.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\CRYPTBASE.DLL:CRYPTBASE.DLL (00007FFEF2950000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\CRYPTBASE.DLL', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\SSPICLI.DLL:SSPICLI.DLL (00007FFEF2E00000), size: 192512 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\SSPICLI.DLL', fileVersion: 6.2.17763.1
C:\Windows\System32\IMM32.DLL:IMM32.DLL (00007FFEF6D30000), size: 188416 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\IMM32.DLL', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FFEE44A0000), size: 2019328 (result: 8), SymType: '-unknown-', PDB: '', fileVersion: 6.2.17763.1
ERROR: LoadModule, GetLastError: 8 (Address: 0000000000000000)
C:\Windows\System32\bcrypt.dll:bcrypt.dll (00007FFEF2FF0000), size: 155648 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\bcrypt.dll', fileVersion: 6.2.17763.1
C:\Windows\system32\uxtheme.dll:uxtheme.dll (00007FFEF12C0000), size: 638976 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\uxtheme.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\imagehlp.dll:imagehlp.dll (00007FFEF5D70000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\imagehlp.dll', fileVersion: 6.2.17763.1
C:\Windows\system32\rsaenh.dll:rsaenh.dll (00007FFEF2340000), size: 208896 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\rsaenh.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\gpapi.dll:gpapi.dll (00007FFEF1C00000), size: 139264 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\gpapi.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\cryptnet.dll:cryptnet.dll (00007FFEED6E0000), size: 192512 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\cryptnet.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\clbcatq.dll:clbcatq.dll (00007FFEF6E10000), size: 663552 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\clbcatq.dll', fileVersion: 2001.12.10941.16384
C:\Windows\SYSTEM32\ntmarta.dll:ntmarta.dll (00007FFEF1FC0000), size: 200704 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ntmarta.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\MSCTF.dll:MSCTF.dll (00007FFEF6B60000), size: 1482752 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\MSCTF.dll', fileVersion: 6.2.17763.348
C:\Windows\system32\dwmapi.dll:dwmapi.dll (00007FFEF1610000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\dwmapi.dll', fileVersion: 6.2.17763.1
C:\Windows\system32\napinsp.dll:napinsp.dll (00007FFEEF8D0000), size: 90112 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\napinsp.dll', fileVersion: 6.2.17763.1
C:\Windows\system32\pnrpnsp.dll:pnrpnsp.dll (00007FFEEF480000), size: 106496 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\pnrpnsp.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\mswsock.dll:mswsock.dll (00007FFEF2780000), size: 421888 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\mswsock.dll', fileVersion: 6.2.17763.292
C:\Windows\SYSTEM32\DNSAPI.dll:DNSAPI.dll (00007FFEF2520000), size: 811008 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DNSAPI.dll', fileVersion: 6.2.17763.292
C:\Windows\System32\NSI.dll:NSI.dll (00007FFEF6EC0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\NSI.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (00007FFEF24E0000), size: 249856 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\IPHLPAPI.DLL', fileVersion: 6.2.17763.1
C:\Windows\System32\winrnr.dll:winrnr.dll (00007FFEEF8C0000), size: 57344 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\winrnr.dll', fileVersion: 6.2.17763.1
C:\Windows\system32\NLAapi.dll:NLAapi.dll (00007FFEEFB50000), size: 110592 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\system32\NLAapi.dll', fileVersion: 6.2.17763.134
C:\Windows\system32\wshbth.dll:wshbth.dll (00007FFEE1970000), size: 86016 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\system32\wshbth.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\fwpuclnt.dll:fwpuclnt.dll (00007FFEEA160000), size: 495616 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\fwpuclnt.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\rasadhlp.dll:rasadhlp.dll (00007FFEEA0A0000), size: 40960 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\rasadhlp.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\TextInputFramework.dll:TextInputFramework.dll (00007FFEDFD10000), size: 610304 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\TextInputFramework.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\CoreUIComponents.dll:CoreUIComponents.dll (00007FFEEE900000), size: 3284992 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\CoreUIComponents.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\CoreMessaging.dll:CoreMessaging.dll (00007FFEF0FC0000), size: 925696 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\System32\CoreMessaging.dll', fileVersion: 6.2.17763.194
C:\Windows\SYSTEM32\wintypes.dll:wintypes.dll (00007FFEEE7A0000), size: 1388544 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\wintypes.dll', fileVersion: 6.2.17763.134
C:\Program Files\YoloMouse\Yolo64.dll:Yolo64.dll (00007FFEE2C00000), size: 331776 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files\YoloMouse\Yolo64.dll'
C:\Windows\SYSTEM32\WindowsCodecs.dll:WindowsCodecs.dll (00007FFEEE380000), size: 1802240 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WindowsCodecs.dll', fileVersion: 6.2.17763.55
D:\Guild Wars 2\bin64\CoherentUI64.dll:CoherentUI64.dll (00007FFECDB70000), size: 1130496 (result: 0), SymType: '-exported-', PDB: 'D:\Guild Wars 2\bin64\CoherentUI64.dll', fileVersion: 1.8.9.4
D:\Guild Wars 2\bin64\d3d9.dll:d3d9.dll (00007FFEDEDE0000), size: 700416 (result: 0), SymType: '-exported-', PDB: 'D:\Guild Wars 2\bin64\d3d9.dll', fileVersion: 0.0.0.1
C:\Windows\SYSTEM32\MSVCR120.dll:MSVCR120.dll (00007FFECE540000), size: 978944 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\MSVCR120.dll', fileVersion: 12.0.21005.1
C:\Windows\SYSTEM32\d3dx9_43.dll:d3dx9_43.dll (00007FFECC7F0000), size: 2502656 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\d3dx9_43.dll', fileVersion: 9.29.952.3111
C:\Windows\SYSTEM32\WINNSI.DLL:WINNSI.DLL (00007FFEEE0A0000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINNSI.DLL', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\DPAPI.dll:DPAPI.dll (00007FFEF2380000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DPAPI.dll', fileVersion: 6.2.17763.1
D:\Guild Wars 2\bin64\d3d9_chainload.dll:d3d9_chainload.dll (00007FFECBF80000), size: 8810496 (result: 0), SymType: 'PDB', PDB: 'D:\Guild Wars 2\bin64\d3d9_chainload.dll'
C:\Windows\SYSTEM32\dxgi.dll:dxgi.dll (00007FFEF1C80000), size: 794624 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dxgi.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\D3DCOMPILER_47.dll:D3DCOMPILER_47.dll (00007FFEEFCE0000), size: 4530176 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\D3DCOMPILER_47.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\VCRUNTIME140.dll:VCRUNTIME140.dll (00007FFEE6910000), size: 94208 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\VCRUNTIME140.dll', fileVersion: 14.0.24215.1
C:\Windows\SYSTEM32\d3d12.dll:d3d12.dll (00007FFEE24A0000), size: 1871872 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\d3d12.dll', fileVersion: 6.2.17763.348
C:\Windows\system32\d3d9.dll:d3d9.dll (00007FFEE9000000), size: 1695744 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\d3d9.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvldumdx.dll:nvldumdx.dll (00007FFEEDE90000), size: 974848 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvldumdx.dll', fileVersion: 25.21.14.1935
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvd3dumx.dll:nvd3dumx.dll (00007FFEBD4F0000), size: 20709376 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvd3dumx.dll', fileVersion: 25.21.14.1935
C:\Windows\SYSTEM32\nvapi64.dll:nvapi64.dll (00007FFEE9B20000), size: 5251072 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\nvapi64.dll', fileVersion: 25.21.14.1935
C:\Windows\System32\SETUPAPI.dll:SETUPAPI.dll (00007FFEF43A0000), size: 4673536 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\SETUPAPI.dll', fileVersion: 6.2.17763.292
C:\Windows\system32\winbrand.dll:winbrand.dll (00007FFEE79E0000), size: 196608 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\winbrand.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\dsound.dll:dsound.dll (00007FFEDEC20000), size: 614400 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dsound.dll', fileVersion: 6.2.17763.348
C:\Windows\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (00007FFEF2D10000), size: 167936 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DEVOBJ.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\DEVRTL.dll:DEVRTL.dll (00007FFEEA080000), size: 77824 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DEVRTL.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\SPINF.dll:SPINF.dll (00007FFEEA0B0000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\SPINF.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\drvstore.dll:drvstore.dll (00007FFEE9680000), size: 1224704 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\drvstore.dll', fileVersion: 6.2.17763.292
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvwgf2umx.dll:nvwgf2umx.dll (00007FFEBB0A0000), size: 38031360 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_7a8e74171e1b8492\nvwgf2umx.dll', fileVersion: 25.21.14.1935
C:\Windows\SYSTEM32\D3DSCache.dll:D3DSCache.dll (00007FFEE4330000), size: 176128 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\D3DSCache.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\twinapi.appcore.dll:twinapi.appcore.dll (00007FFEF1640000), size: 2150400 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\twinapi.appcore.dll', fileVersion: 6.2.17763.292
C:\Windows\SYSTEM32\USERENV.dll:USERENV.dll (00007FFEF2E30000), size: 163840 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\USERENV.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\RMCLIENT.dll:RMCLIENT.dll (00007FFEF1850000), size: 163840 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\RMCLIENT.dll', fileVersion: 6.2.17763.194
C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvStereoApiI64.dll:nvStereoApiI64.dll (00007FFEE29E0000), size: 397312 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvStereoApiI64.dll', fileVersion: 7.17.14.1935
C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll:nvSCPAPI64.dll (00007FFEE9950000), size: 802816 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll', fileVersion: 7.17.14.1935
C:\Windows\SYSTEM32\WINSTA.dll:WINSTA.dll (00007FFEF2060000), size: 360448 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINSTA.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\dcomp.dll:dcomp.dll (00007FFEF0A80000), size: 1847296 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dcomp.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\MMDevApi.dll:MMDevApi.dll (00007FFEECC00000), size: 458752 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\MMDevApi.dll', fileVersion: 6.2.17763.1
C:\Windows\System32\PROPSYS.dll:PROPSYS.dll (00007FFEEF620000), size: 1736704 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\PROPSYS.dll', fileVersion: 7.0.17763.348
C:\Windows\SYSTEM32\wdmaud.drv:wdmaud.drv (00007FFEDEBD0000), size: 278528 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\wdmaud.drv', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\ksuser.dll:ksuser.dll (00007FFEE7420000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ksuser.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\AVRT.dll:AVRT.dll (00007FFEEF090000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\AVRT.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FFEE0A60000), size: 1343488 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\AUDIOSES.DLL', fileVersion: 6.2.17763.348
C:\Windows\SYSTEM32\msacm32.drv:msacm32.drv (00007FFEE47B0000), size: 53248 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\msacm32.drv', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\midimap.dll:midimap.dll (00007FFEE41E0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\midimap.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (00007FFEF1880000), size: 81920 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\resourcepolicyclient.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\mscms.dll:mscms.dll (00007FFEE8690000), size: 708608 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\mscms.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\ColorAdapterClient.dll:ColorAdapterClient.dll (00007FFEEA030000), size: 65536 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ColorAdapterClient.dll', fileVersion: 6.2.17763.1
C:\Windows\SYSTEM32\icm32.dll:icm32.dll (00007FFEE2340000), size: 274432 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\icm32.dll', fileVersion: 6.2.17763.1
c:\projects\d912pxy\thirdparty\stackwalker\stackwalker.cpp (1096): StackWalker::ShowCallstack
c:\projects\d912pxy\d912pxy\d912pxy_helper.cpp (57): d912pxy_helper::VexHandler
c:\projects\d912pxy\d912pxy\d912pxy_helper.cpp (116): d912pxy_helper::VexDbgHandler
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF6F66B06)
00007FFEF6F66B06 (ntdll): (filename not available): RtlInitializeCriticalSectionAndSpinCount
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF6F04849)
00007FFEF6F04849 (ntdll): (filename not available): RtlWalkFrameChain
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF6FA33FE)
00007FFEF6FA33FE (ntdll): (filename not available): KiUserExceptionDispatcher
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEE691C387)
00007FFEE691C387 (VCRUNTIME140): (filename not available): memmove
c:\projects\d912pxy\d912pxy\d912pxy_surface.cpp (312): d912pxy_surface::DelayedLoad
c:\projects\d912pxy\d912pxy\d912pxy_async_upload_thread.cpp (37): d912pxy_async_upload_thread<d912pxy_texture_load_item,d912pxy_texture_loader *>::ThreadJob
c:\projects\d912pxy\d912pxy\d912pxy_thread.cpp (161): d912pxy_thread_main
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FFEF63E81F4)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF63E81F4)
00007FFEF63E81F4 (KERNEL32): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFEF6F6A251)
00007FFEF6F6A251 (ntdll): (filename not available): RtlUserThreadStart

**Additional settings**
Disabled all the optimizations i applied to Nvidia drivers and Gw2-64.exe.

**Additional informations**
Also Discord crashes with the game (No, the problem doesn't depend from Discord).
P.S: Discord's Overlay and Hardware acceleration are disabled.

**Comment by megai2** [comment]
related to upload buffer memory trashing, should be fixed on latest release

**Comment by KleyArk** [comment]
I still have the second type of crash after update to latest release.

**Comment by megai2** [comment]
please check for this crash with a discord overlay only and arcdps only.
also add a p7 log from crash if it have size > 0 bytes.

**Comment by KleyArk** [comment]
**Description**
I tested with only Discord, only ArcDPS and then with both and also with TacO. After 1h of stress test the game is crashed only one time, while i was running Discord (Overlay+Call+Streaming), Firefox Browser (4 websites open), YoloMouse, TacO and ArcDPS all together (which is the normal way i usually play GW2, except for streaming).
P.S: i also tested with OBS Studio, but without addons.

**Standard information**

-Windows 10 1809 (Build 17763.379)
- Hardware info: Intel Core i7 4770 (Hyper Threading ON), Nvidia GTX 1080, RAM HyperX DDR3 16GB 1600Mhz
-Driver version 419.35
- Addon v0.9.7.5 hotfix 1
- Log files from <game root>/addons/arcdps/arcdps.log | <game root>/d912pxy_crash.txt | <game root>/P7logs

**Stress test informations**
Opening all in-game tabs (guild, tp, inventory, weapon preview, friend list, map and character wardrobe), walking around using special action at spam, switching window with alt+tab and using teleport in Mystlock Sanctuary and outside to Lion's Arch.

**Crash Logs ArcDPS**
Mar 18 15:42:12 arcdps 20190309.175644-289-x64
Mar 18 15:42:13 client: gw2 0x7FF708600000-0x7FF70AB08000 (0x9455B404)
Mar 18 15:42:13 client: arcdps 0x7FFE18B90000-0x7FFE18C3B000 (0xF92BCB8D)
Mar 18 15:42:13 client: d3d9 0x7FFDFC830000-0x7FFDFD098000 (0xEFEA14BB)
Mar 18 15:42:13 client: d3d9 is chainload
Mar 18 15:42:14 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 18 15:46:45 error: intercepted crash from hardware exception, terminating
Mar 18 15:46:45 error: exception: 0xC0000005, 0x7FFE1991C387, 2

**Crash Logs D912PXY**
[crash_logs.zip](https://github.com/megai2/d912pxy/files/2978869/crash_logs.zip)

**Comment by KleyArk** [comment]
I'm now playing without ArcDPS and TacO, the game is crashed two times in 1-2hrs (my friend is crashed 3 times with the same error in the log) with the same d912pxy error that i reported in my last comment. The only difference is that if you don't use ArcDPS then you see a message from the game saying "Gw2-64.exe is crashed, report error...".
This may occur in different situations:
- Teleporting to a Waypoint
- Checking your inventory
- Using merchants
- Walking around (Raid Deimos and Mystlock Sanctuary in my cases)

Hope this can help you somehow :)

**Comment by megai2** [comment]
recheck on r150+

**Comment by KleyArk** [comment]
Ok, i'm testing the new version.
Anyway i found a little graphic bug. Look at the sun in the screenshots below.

**Screenshot**
Vehtendi Academy in Domain of Vabbi, this happen also outside.
![gw062](https://user-images.githubusercontent.com/45238047/54570336-7a9a2300-49de-11e9-900e-0a0ac2cefaf5.jpg)
![gw063](https://user-images.githubusercontent.com/45238047/54570451-cd73da80-49de-11e9-92a5-9cd0669ab0c7.jpg)
![gw061](https://user-images.githubusercontent.com/45238047/54570455-d06ecb00-49de-11e9-93a7-bb5d3e789983.jpg)

**Comment by SpatiumPrinceps** [comment]
**Description**
Not sure if its the same problem or another one. Playing just with arcdps+buildtemplates. Walking around the huge crystal in hoelbrak. Also crashed with the release before 150, that was posted on reddit.
No overlays used. 
No crash for 5h playing dungeons / hot events / ls3 maps.

**Standard information**
Virtualised Windows 10 Enterprise 10.0.17134
8700k (4 cores in vm), 16GB, GTX1060 (virtualised with VFIO)
Nvidia 419.17
d912pxy_v0.9.7.5.2b_r151

**Crash Logs ArcDPS**
Mar 19 10:49:57 arcdps 20190309.175644-289-x64
Mar 19 10:49:58 client: gw2 0x7FF6823D0000-0x7FF6848D8000 (0x9455B404)
Mar 19 10:49:58 client: arcdps 0x7FF8129A0000-0x7FF812A4B000 (0xF92BCB8D)
Mar 19 10:49:58 client: d3d9 0x7FF8088B0000-0x7FF809118000 (0xE1A55E55)
Mar 19 10:49:58 client: d3d9 is chainload
Mar 19 10:49:58 extensions: buildtemplates 0x7FF81B3A0000-0x7FF81B3B3000 (20190305.201717-289-x64, 0x7621E183)
Mar 19 10:49:58 config: loading from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 19 12:47:24 error: reached 1000ms timeout on lock 0x29f8 (at arcdps\arcdps_hooks.cpp, 194)
Mar 19 15:15:31 error: intercepted crash from hardware exception, terminating
Mar 19 15:15:31 error: exception: 0xC0000005, 0x7FF8088BD694, 2
[logs.zip](https://github.com/megai2/d912pxy/files/2983828/logs.zip)

**Comment by megai2** [comment]
> 
> 
> **Description**
> Not sure if its the same problem or another one. Playing just with arcdps+buildtemplates. Walking around the huge crystal in hoelbrak. Also crashed with the release before 150, that was posted on reddit.
> No overlays used.
> No crash for 5h playing dungeons / hot events / ls3 maps.
> 
> **Standard information**
> Virtualised Windows 10 Enterprise 10.0.17134
> 8700k (4 cores in vm), 16GB, GTX1060 (virtualised with VFIO)
> Nvidia 419.17
> d912pxy_v0.9.7.5.2b_r151
> 
> **Crash Logs ArcDPS**
> Mar 19 10:49:57 arcdps 20190309.175644-289-x64
> Mar 19 10:49:58 client: gw2 0x7FF6823D0000-0x7FF6848D8000 (0x9455B404)
> Mar 19 10:49:58 client: arcdps 0x7FF8129A0000-0x7FF812A4B000 (0xF92BCB8D)
> Mar 19 10:49:58 client: d3d9 0x7FF8088B0000-0x7FF809118000 (0xE1A55E55)
> Mar 19 10:49:58 client: d3d9 is chainload
> Mar 19 10:49:58 extensions: buildtemplates 0x7FF81B3A0000-0x7FF81B3B3000 (20190305.201717-289-x64, 0x7621E183)
> Mar 19 10:49:58 config: loading from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
> Mar 19 12:47:24 error: reached 1000ms timeout on lock 0x29f8 (at arcdps\arcdps_hooks.cpp, 194)
> Mar 19 15:15:31 error: intercepted crash from hardware exception, terminating
> Mar 19 15:15:31 error: exception: 0xC0000005, 0x7FF8088BD694, 2
> [logs.zip](https://github.com/megai2/d912pxy/files/2983828/logs.zip)

#105

I close this issue for now as source of original crash is fixed, will reopen if something specific to addons/overlays will be found

**Comment by KleyArk** [comment]
I'm sorry to annunce you that the problem is still there. Maybe in a different manner.

There're no P7logs.

**Crash logs ArcDPS**
Mar 19 10:35:37 arcdps 20190309.175644-289-x64
Mar 19 10:35:38 client: gw2 0x7FF7AFBC0000-0x7FF7B20C8000 (0x9455B404)
Mar 19 10:35:38 client: arcdps 0x7FFF6E560000-0x7FFF6E60B000 (0xF92BCB8D)
Mar 19 10:35:38 client: d3d9 0x7FFF62B90000-0x7FFF633F8000 (0xE1A55E55)
Mar 19 10:35:38 client: d3d9 is chainload
Mar 19 10:35:39 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 19 11:03:23 error: intercepted crash from hardware exception, terminating
Mar 19 11:03:23 error: exception: 0xE06D7363, 0x7FFF91159149, 4

**Crash logs P912PXY**
0 | "hlsl generator not support shader model specified" | hr = FFFFFFFF 
1 | "shader replace error" | hr = FFFFFFFF 
0 | d912pxy_global_objects::DXDev->CreateCommittedResource( &rhCfg, D3D12_HEAP_FLAG_NONE, &rsDesc, D3D12_RESOURCE_STATE_GENERIC_READ, 0, __uuidof(**(&m_res)), IID_PPV_ARGS_Helper(&m_res) ) | hr = 887A0005 
SymInit: Symbol-SearchPath: '.;D:\Guild Wars 2;D:\Guild Wars 2;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'User'
0 | "texture object create failed" | hr = 887A0005 
OS-Version: 6.2.9200 () 0x100-0x1
D:\Guild Wars 2\Gw2-64.exe:Gw2-64.exe (00007FF7AFBC0000), size: 38830080 (result: 0), SymType: '-nosymbols-', PDB: 'D:\Guild Wars 2\Gw2-64.exe', fileVersion: 1.0.0.1

**Comment by megai2** [comment]
Please send full log to report issue #13

**Comment by KleyArk** [comment]
What i copied here is the full log, cause there's no P7log (all =0kb).
