### ISSUE TITLE
[visual] HoT story instance all cutscenes dark and blurry.

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#220]
> > In Heart of Thorns in story instance all cutscenes are blurry and very dark. I'm using Version 1.9 hotfix 2. After solution from this post https://github.com/megai2/d912pxy/wiki/Reporting-visual-errors cutscene was ok for 2 seconds and then again turned to dark and blurry.
> > ![gw250](https://user-images.githubusercontent.com/22241229/72755735-45e99000-3bdc-11ea-98cf-4fe36412949a.jpg)
> > ![gw251](https://user-images.githubusercontent.com/22241229/72755736-45e99000-3bdc-11ea-97bc-15f95c8ec8e8.jpg)
> > [log.txt](https://github.com/megai2/d912pxy/files/4087793/log.txt)
> 
> can you upload /d912pxy/shaders/hlsl/err_A9495E52BA2F7817.hlsl too?

Sure! Here it is. And this problem is very strange cause during my walkthrough Heart of Thorns I've seen it 3 times and other cutscenes (both with and without player's character) was ok. I can't name difference between cutscenes with bag and without it. But I'm sure that bag appeared after this tip https://github.com/megai2/d912pxy/wiki/Reporting-visual-errors at least one time. P.S. Your program is awesome, huge FPS boost)) Thank you very much for it)))
[err_A9495E52BA2F7817.zip](https://github.com/megai2/d912pxy/files/4093604/err_A9495E52BA2F7817.zip)

_Originally posted by @MirGLAB in https://github.com/megai2/d912pxy/issues/15#issuecomment-576873749_

**Comment by megai2** [comment]
shader have 2 color outputs, should be sorted

**Comment by Raazael** [comment]
I have this issue as well. 6 months later, is there a fix for the issue?

**Comment by megai2** [comment]
shader uses multiple render targets that are not yet supported in whole d912pxy,
i added a workaround, maybe it will work out, look latest build

**Comment by MasterJam-ai** [comment]
also on latest release 2.1.2 this problem exist - also the issue when GW2 crashes when minimizing or windowing the game. Any update for an upcoming release to test?

**Comment by Renkindle** [comment]
I've also been having this issue and just installed the latest build yesterday.
I also had a separate visual error occur more than this one where the whole cutscene looked like the sky glitching out - 
![image](https://user-images.githubusercontent.com/29805723/88266352-1ad01e00-cc9d-11ea-9ecf-e416900040c7.png)

**Comment by megai2** [comment]
Quick test on r597 showed that bug is solved (via MRT support addition)

**Comment by Ghostkat9** [comment]
> Quick test on r597 showed that bug is solved (via MRT support addition)

Still having this problem in PoF cutscenes. Is there a fix for it yet?

**Comment by megai2** [comment]
> 
> 
> > Quick test on r597 showed that bug is solved (via MRT support addition)
> 
> Still having this problem in PoF cutscenes. Is there a fix for it yet?

Fix is not in releases yet, only in appveyor builds 
https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by megai2** [comment]
fixed in v2.3
