### ISSUE TITLE
New Update broke Character Select and NPC icons

### ISSUE THREAD

**Issue by Manaci** [megai2/d912pxy#275]
The latest update (2.2) introduced a new bug where the character select and NPC icons are totally screwed up and won't load correctly even if you re-click the NPCs (that was the old bug that was more bearable). Now some NPC icons have the hair in the opposite direction, no helm, head is off-center, head is inside body etc. This is looking really weird.
![hmmmm](https://user-images.githubusercontent.com/26745981/88795038-acf58c00-d19f-11ea-8eff-463c911ea871.png)
![wtf is this](https://user-images.githubusercontent.com/26745981/88795040-ad8e2280-d19f-11ea-818b-208098aac654.png)
![lol](https://user-images.githubusercontent.com/26745981/88795041-ae26b900-d19f-11ea-9f9b-9f485c0e047c.png)

**Comment by StonedAstronaut** [comment]
Same.
I tried doing this [https://github.com/megai2/d912pxy/wiki/Fixing-character-portraits-at-character-select](https://github.com/megai2/d912pxy/wiki/Fixing-character-portraits-at-character-select) . But didn't help.

**Comment by kazerniel** [comment]
> 
> 
> Same.
> I tried doing this https://github.com/megai2/d912pxy/wiki/Fixing-character-portraits-at-character-select . But didn't help.

Same. The character selection fix worked in previous versions, now did it twice and it still doesn't.

**Comment by WanYaa** [comment]
there might be a fix from anet on the way for this as far as I followed discord communication
no eta yet though as the coding they changed for portraits does not break the unmodded game

**Comment by Fexul** [comment]
Weirds faces in portraits as Manaci said.

**Comment by megai2** [comment]
Wait for fix from ArenaNet as they broke depth buffer for portraits.

**Comment by ideka** [comment]
Can they really be expected to fix this "bug" if it doesn't cause any problems in vanilla?

**Comment by Straatman4** [comment]
Hello! Do you know if there is any solutions right now? Thx :D

**Comment by megai2** [comment]
Looks like ignoring depth set and keeping it setted to previous surface is safe-enough.
I'll put ignore instead of disable depth, so portraits will be fine, but bug still be around and can break something.

**Comment by gotyaoi** [comment]
Just logged in with the festival update, still on d912pxy 2.2, and it seems to have been fixed?

**Comment by Straatman4** [comment]
@megai2 do i have to change something? I still have the same problem with portraits :(

**Comment by megai2** [comment]
> 
> 
> @megai2 do i have to change something? I still have the same problem with portraits :(

you need to use latest revision from appveyor right now
i'll update release on weekend if all goes well

**Comment by megai2** [comment]
fixed in v2.2.1
